### ISSUE TITLE
aosp ch3 build遇到問題

### ISSUE THREAD

**Issue by y78078** [TADSG/aosp-study#21]
從ch1-setup -> ch3-build 全程使用vmplayer環境，OS使用Ubuntu 14.04 LTS

以下為build完以後的狀況，不能emulator，請各大大幫忙一下小弟

![image](https://cloud.githubusercontent.com/assets/22907650/19542355/104f9352-96a0-11e6-815e-a7b88a40031a.png)

另問提供之實驗環境（VMware Workstation Pro 12.1.1 + Ubuntu 14.04.4 LTS + AOSP 6.0.1_r60 + Nexus 5 Binaries + Nexus 5 Images Built）

1.請問還要build嗎?
2.如果單純想要使用該版本用來玩emulator，大概要怎樣做。
# ------------------------------------------------------------------------------------------------------------------

另ch3內一文
"使用模擬器開發建議啟用 HAXM 加速，Linux 上啟用 HAXM 請參考 How to Start Intel Hardware-assisted Virtualization (hypervisor) on Linux to Speed-up Intel Android x86 Emulator"

Intel網頁上面中間有一工具ia32-libs-multiarch已列入old-releases，目前是使用下面網頁的方法去安裝
http://stackoverflow.com/questions/23182765/how-to-install-ia32-libs-in-ubuntu-14-04-lts-trusty-tahr
# ------------------------------------------------------------------------------------------------------------------

另有聽說andriod 5.0以上版本如果build環境開2G會常常build error，建議要4G以上。(小弟電腦不夠好以前都切2G，現在切4G給他跑跑看)
# ------------------------------------------------------------------------------------------------------------------

 Note: repo sync 過程中經常出現  request fail / fetch errors

**Comment by chartsai** [comment]
emulator的問題，必需要先成功clean build出來才能用。該image應該是已經build好了。
如果是針對Nexus5去build的話，就沒辦法用emulator。不同裝置(含emulator)因為CPU架構/指令集等會有不同，所以不同裝置必需分開build噢~

HAXM的部份感謝回報，請問你/妳有興趣發PR更新成新版的文件嗎？

**Comment by y78078** [comment]
PR?
clean build的話，意思是要下make clobber?

**Comment by chartsai** [comment]
Pull Request~就是邀你一請寫這份文件的意思
對的，clean build要下make clobber

**Comment by y78078** [comment]
Dear Charlie

```
  昨天忘記說了PR OK阿，不過小弟我在你第一次講aosp的時候，還沒來台北工作，linux沒碰過更不用說IOS，
  所以可能還很多東西不懂，連git github都沒聽過，也怕會寫錯，還要跟大家多多學習。

  不知道大家通常在哪邊問問題?因為GitHub好像沒什麼人在問。
  至於昨天提到的lunch 後 數字可能會跟官方提供的不太一樣，我這邊ubuntu14.04.4 虛擬機好像是沒問題的。
```

have a nice google team

Michael Lin

2016-10-25 18:04 GMT+08:00 Charlie Tsai notifications@github.com:

**Comment by chartsai** [comment]
大家太客氣才少在github上問，通常是在telegram群組問～
不過我覺得開issue很好，因為會有記錄不會被洗掉XD
